### ISSUE TITLE
File.File() no longer works

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2075]
This issue was originally created at: 2008-05-27 22:48:32.
This issue was reported by: `mhorowitz`.
mhorowitz said at 2008-05-27 22:48:32
>(I suspect the bug is platform and OS-independent, but I only verified on the
>above system)
> 
>this SConstruct file:
> 
>import SCons
> 
>env = Environment()
> 
>foo = env.File("foo")
>bar = foo.File("bar")
> 
>fails:
> 
>scons: Reading SConscript files ...
>AttributeError: 'NoneType' object has no attribute 'File':
>  File "C:\Documents and Settings\marc\Desktop\azrael\src\branches\windows2-deve
>l\client-common\x\SConstruct", line 8:
>    bar = foo.File("bar")
>  File "C:\Python25\Lib\site-packages\scons-0.98.3\SCons\Node\FS.py", line 2165:
>    return self.cwd.File(name)
> 
>Looking at FS.py, it looks like self.cwd is never initialized for File objects.
> The same test works on a linux box running 0.97.something, which looks likely
>given the code changes.  Looking at 0.98.4 in the repo, nothing seems to have
>been done to fix it.

stevenknight said at 2008-05-28 16:43:36
>As Marc says, this works in 0.97, but looks like it was introduced right away in 
>0.97.0d20070809.  I reproduce it just fine on a Linux system.
> 
>I'm setting the target milestone to 0.98.5 and upping the priority to P2 so we 
>fix the regression before 1.0.  If it looks hairy or potentially destabilizing 
>for 1.0, I'll lower the priority and push back the target milestone.
> 

stevenknight said at 2008-05-29 08:24:47
>Fixed in next release (0.98.5) by the following checkin:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5803
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1564
> 
>Thanks for the report,
>
