### ISSUE TITLE
top relative #/dir not working 

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#191]
This issue was originally created at: 2002-04-05 19:47:40.
This issue was reported by: `issues@scons`.
issues@scons said at 2002-04-05 19:47:40
>The syntax
> 
>  env = Environment(CPPPATH='#/include')
> 
>does not work with either SCons 0.05 or 0.06, although 
>it's directly from the man page (0.06, line 531). 
>However,
> 
>  env = Environment(CPPPATH='#./include')
>  env = Environment(CPPPATH='#include')
> 
>do work with both versions. "Does not work" produces 
>the messages:
> 
>$ scons
>cl /nologo /I\include /c src\hello.c /Fosrc\hello.obj
>hello.c
>src\hello.c(2) : fatal error C1083: Cannot open 
>include file: 'hello.h': No
>such file or directory
>scons: *** [src\hello.obj] Error 2
> 
>For more info and a simple test case see
> 
>http://www.geocrawler.com/lists/3/SourceForge/13500/0/8
>300853/

issues@scons said at 2002-04-05 19:47:40
>Converted from SourceForge tracker item 540092
